# Generated by Django 5.0.4 on 2024-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistes',
            fields=[
                ('id_artiste', models.AutoField(primary_key=True, serialize=False)),
                ('pseudounymes', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('biographie', models.CharField(max_length=2000)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oeuvre_art',
            fields=[
                ('id_oeuvre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images/')),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reservation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
            ],
        ),
    ]
