# Generated by Django 5.0.4 on 2024-05-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_art', '0002_categorie_rename_id_artiste_artistes_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='En_Location',
        ),
    ]
