# Generated by Django 5.0.6 on 2024-05-29 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_art', '0003_rename_location_en_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='oeuvre_art',
            name='artistes',
        ),
        migrations.AddField(
            model_name='categorie',
            name='oeuvre_art',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_art.oeuvre_art'),
        ),
        migrations.AddField(
            model_name='clients',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='oeuvre_art',
            name='pseudo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistes',
            name='pseudounymes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
