# Generated by Django 5.0.4 on 2024-11-19 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_art', '0008_profil_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre_art',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oeuvre_art',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oeuvre_art',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oeuvre_art',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oeuvre_art',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='oeuvre_art',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
